repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-vcs-permalinks
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
  - repo: https://github.com/PrincetonUniversity/blocklint
    rev: v0.2.4
    hooks:
      - id: blocklint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint
  - repo: local
    hooks:
      - id: alejandra
        name: Alejandra formatter for Nix files.
        language: system
        entry: nix
        args: ["fmt", "||", "true"]
